version: "3.8"
services:
  processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
    container_name: processor
    ports:
      - "5001:5001"
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    environment:
      - PROCESSOR_URL=http://processor:5001/process
    ports:
      - "5000:5000"
    depends_on:
      - processor
